apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: app-
metadata:
  name: weaviate-ressources
commonLabels:
  app: weaviate

resources:
- ./base

configMapGenerator:
- name: weaviate-config
  envs:
  - ./configmap.env