apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/service: weaviate
  name: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/service: weaviate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/service: weaviate
    spec:
      containers:
        - args:
            - --host
            - 0.0.0.0
            - --port
            - "8080"
            - --scheme
            - http
          env:
            - name: WEAVIATE_HOST
              valueFrom:
                configMapKeyRef:
                  name: weaviate-configmap
                  key: WEAVIATE_HOST
            - name: AUTHENTICATION_APIKEY_ALLOWED_KEYS
              valueFrom:
                secretKeyRef:
                  name: weaviate-secret
                  key: ALLOWED_API_KEYS
            - name: AUTHENTICATION_APIKEY_ENABLED
              value: "true"
            - name: AUTHENTICATION_APIKEY_USERS
              valueFrom:
                secretKeyRef:
                  name: weaviate-secret
                  key: API_KEYS_USERS
            - name: CLUSTER_HOSTNAME
              value: node1
            - name: DEFAULT_VECTORIZER_MODULE
              value: text2vec-huggingface
            - name: ENABLE_MODULES
              value: text2vec-huggingface # secret
            - name: HUGGINGFACE_APIKEY
              valueFrom:
                secretKeyRef:
                  name: weaviate-secret
                  key: HUGGINGFACE_APIKEY
            - name: LOG_LEVEL
              value: debug
            - name: PERSISTENCE_DATA_PATH
              value: /var/lib/weaviate
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
          image: semitechnologies/weaviate:1.20.5
          name: weaviate
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/weaviate
              name: weaviate-data
      restartPolicy: Always
      volumes:
        - name: weaviate-data
          persistentVolumeClaim:
            claimName: weaviate-data