apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/service: weaviate
  name: weaviate
  namespace: default
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/service: weaviate
