apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: weaviate
  labels:
    name: weaviate
    app: weaviate
    app.kubernetes.io/name: weaviate
spec:
  replicas: 1
  serviceName: weaviate-headless
  selector:
    matchLabels:
      app: weaviate
  template:
    metadata:
      labels:
        app: weaviate
        app.kubernetes.io/name: weaviate
      annotations:
        # To restart Pods if the ConfigMap is updated.
        checksum/config: afd1a2f41321078026750ff7395e4418b073a86658409e1a2ce7b77efe371c5b
    spec:
      securityContext:
        {}
      terminationGracePeriodSeconds: 600
      initContainers:
      - name: configure-sysctl
        securityContext:
          runAsUser: 0
          privileged: true
        image: "docker.io/alpine:latest"
        imagePullPolicy: "IfNotPresent"
        command: ["sysctl", "-w", "vm.max_map_count=524288", "vm.overcommit_memory=1" ]
      containers:
      - name: weaviate
        image: 'docker.io/semitechnologies/weaviate:$IMAGE_VERSION'
        imagePullPolicy: IfNotPresent
        command: 
          - /bin/weaviate
        args: 
          - --host
          - 0.0.0.0
          - --port
          - "8080"
          - --scheme
          - http
          - --config-file
          - /weaviate-config/conf.yaml
          - --read-timeout=60s
          - --write-timeout=60s
        resources:
          {}
        env:
          - name: WEAVIATE_HOST
            valueFrom:
              configMapKeyRef:
                name: weaviate-config
                key: WEAVIATE_HOST            
          - name: CLUSTER_DATA_BIND_PORT
            value: "7001"
          - name: CLUSTER_GOSSIP_BIND_PORT
            value: "7000"
          - name: GOGC
            value: "100"
          - name: PROMETHEUS_MONITORING_ENABLED
            value: "false"
          - name: QUERY_MAXIMUM_RESULTS
            value: "100000"
          - name: REINDEX_VECTOR_DIMENSIONS_AT_STARTUP
            value: "false"
          - name: TRACK_VECTOR_DIMENSIONS
            value: "false"
          - name: STANDALONE_MODE
            value: 'true'
          - name: PERSISTENCE_DATA_PATH
            value: '/var/lib/weaviate'
          - name: DEFAULT_VECTORIZER_MODULE
            value: none
          - name: CLUSTER_JOIN
            value: weaviate-headless.default.svc.cluster.local
          - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
            valueFrom:
              configMapKeyRef:
                name: weaviate-config
                key: WEAVIATE_ANONYMOUS_ACCESS_ENABLED             
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: weaviate-config
            mountPath: /weaviate-config
          - name: weaviate-data
            mountPath: /var/lib/weaviate
        livenessProbe:
          httpGet:
            path: /v1/.well-known/live
            port: 8080
          initialDelaySeconds: 900
          periodSeconds: 10
          failureThreshold: 30
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /v1/.well-known/ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
      volumes:
        - name: weaviate-config
          configMap:
            name: weaviate-config
        - name: weaviate-data
          persistentVolumeClaim:
            claimName: weaviate-data
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - weaviate
              topologyKey: kubernetes.io/hostname
            weight: 1